services:
  beatrizguimaraes_frontend_prod:
    environment:
      - AUTH_URL_INTERNAL=${AUTH_URL_INTERNAL}
      - AUTH_SECRET=${AUTH_SECRET}
      - PORT=6200
    user: node
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: beatrizguimaraes_frontend_prod
    ports:
      - "6200:6200"
    restart: always
